[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"
customer_id = "mdanzinger"
service = "multiplay_billing"

[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

 [[outputs.file]] 
  files = ["stdout", "/tmp/metrics.out"]
  #data_format = "json"
  data_format = "ubazzar"

 [[inputs.net]]

 [[aggregators.basicstats]]
   period = "15s"
   drop_original = true
   stats = ["diff"]
   namepass = ["net"]
   fielddrop = ["total_net_usage_bytes", "quantity"]
   [aggregators.basicstats.tags]
     unit_of_measure = "net-eu-west-mb"

 [[processors.sum]]
 field_key = "total_net_usage_bytes"
 field_sum = ["bytes_recv_diff", "bytes_sent_diff"]

 [[processors.byteconvert]]
  field_src = "total_net_usage_bytes"
  field_name = "quantity"
  format = "mb"


